const mockdata = [
  {
    id: 1,
    name: 'Beige Trench Coat',
    colors: ['Beige'],
    gender: 'Men',
    size: 'One Size',
    category: 'Outwear',
    price: 120,
    imgs: './assets/item-images/beige-trench-thinlayer-man/',
    imgs_length: 2,
  },
  {
    id: 2,
    name: 'Cheongsam',
    colors: ['red', 'white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Dress',
    price: 70,
    imgs: './assets/item-images/cheongsam/',
    imgs_length: 3,
  },
  {
    id: 3,
    name: 'Hoodies',
    colors: ['orange', 'black'],
    gender: 'Women',
    size: 'One Size',
    category: 'Top',
    price: 50,
    imgs: './assets/item-images/hoodies/',
    imgs_length: 2,
  },
  {
    id: 4,
    name: 'Jean Jacket',
    colors: ['blue'],
    gender: 'Women',
    size: 'One Size',
    category: 'Jacket',
    price: 50,
    imgs: './assets/item-images/jean-jacket/',
    imgs_length: 3,
  },
  {
    id: 5,
    name: 'Just Tshirt',
    colors: ['white', 'black'],
    gender: 'Women',
    size: 'One Size',
    category: 'Top',
    price: 20,
    imgs: './assets/item-images/just-tshirt-woman/',
    imgs_length: 2,
  },
  {
    id: 6,
    name: 'Leather Jacket',
    colors: ['black'],
    gender: 'Women',
    size: 'One Size',
    category: 'Jacket',
    price: 80,
    imgs: './assets/item-images/leather-jacket/',
    imgs_length: 2,
  },
  {
    id: 7,
    name: 'Python Top',
    colors: ['grey'],
    gender: 'Women',
    size: 'One Size',
    category: 'Top',
    price: 30,
    imgs: './assets/item-images/python-top/',
    imgs_length: 4,
  },
  {
    id: 8,
    name: 'Croptop Pants Set',
    colors: ['red'],
    gender: 'Women',
    size: 'One Size',
    category: 'Set',
    price: 100,
    imgs: './assets/item-images/croptop-pants-set/',
    imgs_length: 2,
  },
  {
    id: 9,
    name: 'Red Square Shirt',
    colors: ['red'],
    gender: 'Men',
    size: 'One Size',
    category: 'Top',
    price: 60,
    imgs: './assets/item-images/red-square-shirt/',
    imgs_length: 2,
  },
  {
    id: 10,
    name: 'Silver Jacket',
    colors: ['Silver'],
    gender: 'Men',
    size: 'One Size',
    category: 'Jacket',
    price: 70,
    imgs: './assets/item-images/silver-jacket/',
    imgs_length: 3,
  },
  {
    id: 11,
    name: 'Silver Maxi Dress',
    colors: ['Silver'],
    gender: 'Women',
    size: 'One Size',
    category: 'Dress',
    price: 70,
    imgs: './assets/item-images/silver-maxi-dress/',
    imgs_length: 4,
  },
  {
    id: 12,
    name: 'Stripe Shirtdress',
    colors: ['red'],
    gender: 'Women',
    size: 'One Size',
    category: 'Dress',
    price: 60,
    imgs: './assets/item-images/stripe-shirtdress/',
    imgs_length: 2,
  },
  {
    id: 13,
    name: 'Suit Set',
    colors: ['pink', 'black', 'white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Dress',
    price: 110,
    imgs: './assets/item-images/suit-set/',
    imgs_length: 3,
  },
  {
    id: 14,
    name: 'Fall Trench Coat',
    colors: ['light grey', 'khaki', 'white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Outwear',
    price: 120,
    imgs: './assets/item-images/fall-trench-coat/',
    imgs_length: 3,
  },
  {
    id: 15,
    name: 'White Jumpsuit',
    colors: ['white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Set',
    price: 90,
    imgs: './assets/item-images/white-jumpsuit/',
    imgs_length: 3,
  },
  {
    id: 16,
    name: 'White Polkadot Dress',
    colors: ['white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Dress',
    price: 65,
    imgs: './assets/item-images/white-polkadot-dress/',
    imgs_length: 3,
  },
  {
    id: 17,
    name: 'White Stripe Pants',
    colors: ['navy'],
    gender: 'Women',
    size: 'One Size',
    category: 'Pants',
    price: 50,
    imgs: './assets/item-images/white-stripe-pants/',
    imgs_length: 5,
  },
  {
    id: 18,
    name: 'White Suit',
    colors: ['white'],
    gender: 'Women',
    size: 'One Size',
    category: 'Jacket',
    price: 55,
    imgs: './assets/item-images/white-suit/',
    imgs_length: 2,
  },
  {
    id: 19,
    name: 'Wine Red Croptop Set',
    colors: ['wine red'],
    gender: 'Women',
    size: 'One Size',
    category: 'Set',
    price: 115,
    imgs: './assets/item-images/wine-red-croptop-set/',
    imgs_length: 2,
  },
  {
    id: 20,
    name: 'Winter Trench Coat',
    colors: ['Brown', 'light pink'],
    gender: 'Women',
    size: 'One Size',
    category: 'Outwear',
    price: 120,
    imgs: './assets/item-images/winter-trench-coat/',
    imgs_length: 2,
  },
];

export { mockdata };
